version: '3.7'
services:
  jdk:
    command: ["java", "-jar", "/opt/app/db-api-for-docker.jar"]
    build:
      context: ./
      dockerfile: Dockerfile
    image: openjdk:8-slim
    ports:
      - '9999:9999'
    volumes:
      - ./:/opt/app:rw